# Generated by Django 5.2.4 on 2025-08-07 08:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationemplacement',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterModelOptions(
            name='camion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commandefranchise',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AlterModelOptions(
            name='detailcommande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emplacement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancecamion',
            options={'ordering': ['-date_maintenance']},
        ),
        migrations.AlterModelOptions(
            name='paiementredevance',
            options={'ordering': ['-date_echeance']},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockentrepot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ventefranchise',
            options={'ordering': ['-date_vente']},
        ),
        migrations.RemoveField(
            model_name='affectationemplacement',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='annee_fabrication',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='date_derniere_revision',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='prochaine_revision',
        ),
        migrations.RemoveField(
            model_name='categorieproduit',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='commandefranchise',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='commandefranchise',
            name='date_livraison_reelle',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='type_achat',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='emplacement',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='entrepot',
            name='capacite_max',
        ),
        migrations.RemoveField(
            model_name='entrepot',
            name='email',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='nom_gerant',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='prenom_gerant',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='maintenancecamion',
            name='kilometrage_maintenance',
        ),
        migrations.RemoveField(
            model_name='maintenancecamion',
            name='prochaine_echeance',
        ),
        migrations.RemoveField(
            model_name='paiementredevance',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='paiementredevance',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='entrepot_principal',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock_minimum',
        ),
        migrations.RemoveField(
            model_name='ventefranchise',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='ventefranchise',
            name='statut',
        ),
        migrations.AddField(
            model_name='produit',
            name='is_obligatoire',
            field=models.BooleanField(default=False, help_text='Produit de la liste des 80% obligatoires'),
        ),
        migrations.AlterField(
            model_name='commandefranchise',
            name='numero_commande',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='type_zone',
            field=models.CharField(choices=[('centre_ville', 'Centre-ville'), ('zone_commerciale', 'Zone commerciale'), ('parc', 'Parc'), ('entreprise', 'Entreprise'), ('marche', 'Marché')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='droit_entree',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='maintenancecamion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenancecamion',
            name='type_maintenance',
            field=models.CharField(choices=[('revision', 'Révision'), ('reparation', 'Réparation'), ('panne', 'Panne'), ('controle_technique', 'Contrôle technique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiementredevance',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('retard', 'En retard')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='gestion_camions.categorieproduit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('litre', 'Litre'), ('piece', 'Pièce'), ('portion', 'Portion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventefranchise',
            name='redevance_due',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.DeleteModel(
            name='LogAction',
        ),
    ]
