# Generated by Django 5.2.4 on 2025-08-10 23:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0002_alter_affectationemplacement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandefranchise',
            name='montant_libre',
        ),
        migrations.RemoveField(
            model_name='commandefranchise',
            name='montant_obligatoire',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur_principal',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='is_obligatoire',
        ),
        migrations.AddField(
            model_name='commandefranchise',
            name='montant_drivn_cook',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant des produits Driv'n Cook (80% minimum)", max_digits=10),
        ),
        migrations.AddField(
            model_name='commandefranchise',
            name='montant_fournisseur_libre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant des produits libres (20% maximum)', max_digits=10),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='entrepot_livraison',
            field=models.ForeignKey(default=1, help_text="Entrepôt d'où vient le produit (détermine le statut 80/20)", on_delete=django.db.models.deletion.PROTECT, to='gestion_camions.entrepot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepot',
            name='type_entrepot',
            field=models.CharField(choices=[('drivn_cook', "Entrepôt Driv'n Cook (80% obligatoire)"), ('fournisseur_libre', 'Fournisseur libre (20% maximum)')], default='drivn_cook', help_text="Définit si l'entrepôt fait partie des 4 entrepôts Driv'n Cook obligatoires", max_length=20),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
