# Generated by Django 5.2.4 on 2025-08-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0003_remove_commandefranchise_montant_libre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationemplacement',
            options={'ordering': ['-date_debut'], 'verbose_name': "Affectation d'emplacement", 'verbose_name_plural': "Affectations d'emplacements"},
        ),
        migrations.AlterModelOptions(
            name='emplacement',
            options={'verbose_name': 'Emplacement', 'verbose_name_plural': 'Emplacements'},
        ),
        migrations.AddField(
            model_name='emplacement',
            name='franchises_autorisees',
            field=models.ManyToManyField(blank=True, help_text='Franchises autorisées à utiliser cet emplacement', related_name='emplacements_autorises', to='gestion_camions.franchise'),
        ),
        migrations.CreateModel(
            name='AutorisationEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_autorisation', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, help_text='Laisser vide pour une autorisation permanente', null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'autorisation (conditions particulières, etc.)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='gestion_camions.emplacement')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_emplacements', to='gestion_camions.franchise')),
            ],
            options={
                'verbose_name': "Autorisation d'emplacement",
                'verbose_name_plural': "Autorisations d'emplacements",
                'unique_together': {('franchise', 'emplacement')},
            },
        ),
    ]
