# Generated by Django 5.2.4 on 2025-08-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0004_alter_affectationemplacement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailcommande',
            options={'verbose_name': 'Détail de commande', 'verbose_name_plural': 'Détails de commandes'},
        ),
        migrations.RemoveField(
            model_name='commandefranchise',
            name='entrepot',
        ),
        migrations.AddField(
            model_name='commandefranchise',
            name='adresse_livraison',
            field=models.CharField(blank=True, help_text='Adresse complète de livraison (par défaut : adresse de la franchise)', max_length=500),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='entrepot_livraison',
            field=models.ForeignKey(help_text="Entrepôt d'où vient le produit (détermine le statut 80/20)", on_delete=django.db.models.deletion.PROTECT, related_name='details_livraisons', to='gestion_camions.entrepot'),
        ),
        migrations.AlterUniqueTogether(
            name='detailcommande',
            unique_together={('commande', 'produit', 'entrepot_livraison')},
        ),
    ]
