# Generated by Django 5.2.4 on 2025-08-18 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0005_alter_detailcommande_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Franchisé', 'verbose_name_plural': 'Franchisés'},
        ),
        migrations.AddField(
            model_name='franchise',
            name='commentaire_admin',
            field=models.TextField(blank=True, verbose_name='Commentaire administrateur'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('lien_envoye', 'Lien de paiement envoyé'), ('en_cours', 'Paiement en cours'), ('paye', 'Payé'), ('echec', 'Échec de paiement')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='franchise',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchises_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé - En attente de paiement'), ('paye', 'Payé - Actif'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='en_attente', max_length=20),
        ),
    ]
