# Generated by Django 5.2.4 on 2025-08-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_camions', '0006_alter_franchise_options_franchise_commentaire_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementRedevance',
        ),
    ]
