# Generated by Django 5.2.4 on 2025-08-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
