# Generated by Django 5.2.4 on 2025-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_user_first_name_user_last_name_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_franchise',
            field=models.BooleanField(default=False),
        ),
    ]
